apiVersion: v1
kind: BuildConfig
metadata:
  labels:
    app: rails1
  name: rails1
spec:
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: rails1:latest
  postCommit: {}
  resources: {}
  runPolicy: Serial
  source:
    git:
      ref: master
      uri: https://github.com/det-kgl-bibliotek/testOpenShift.git
    type: Git
  strategy:
    dockerStrategy:
      dockerfilePath: Dockerfile
    type: Docker
  triggers:
  - type: ConfigChange
status:
  lastVersion: 0
