apiVersion: v1
kind: ImageStream
metadata:
  creationTimestamp: null
  labels:
    app: rails1
  name: rails1
spec:
  tags:
  - annotations: null
    from:
      kind: DockerImage
      name: rails1
    generation: null
    importPolicy: {}
    name: latest
status:
  dockerImageRepository: ""
